### ISSUE TITLE
...----

### ISSUE THREAD

**Issue by depe95** [Enygma2002/d2l-price-displayer#7]
I found it...
my bad :D

**Comment by Enygma2002** [comment]
Hi,

Yes, you can change the currency using the currency selector:

![Currency selector](https://camo.githubusercontent.com/707c7c308a35c58e74b9f619f0d9758e3cebfde2/68747470733a2f2f692e696d6775722e636f6d2f6f426d416870362e706e67)

Hope you enjoy the script :)
